feat(button): add link, disabled, secondary, primary design implement…
RnDBNCC/technotic pull request #63
Opened 2023-06-19 17:14 UTC by RifianFernando

feat(button): add link, disabled, secondary, primary design implement…

Developer: Rifian F.

### Task Summary

1. Create button link and fixing colorized
2. create button primary, secondary, link, for disabled buttton

2023-06-20 10:24 UTC, randiadiel commented
Will review ya, dont merge

2023-06-20 10:24 UTC, randiadiel requested changes
Nitip Sendal

2023-06-26 13:02 UTC, randiadiel commented on src/components/Button/styles.ts
> +import { generateDefaultPrimarySecondaryButtonStyles } from './utils/StylesGenerator';
Sebenernya kalo utils namanya ga PascalCase. Tapi camelCase

2023-06-28 17:47 UTC, RifianFernando commented on src/components/Button/index.tsx
> +    const color = { backgroundColor: btnColor, border: btnColor };
Oke ko done ko

2023-06-28 17:56 UTC, RifianFernando commented on src/components/Button/styles.ts
> +import { generateDefaultPrimarySecondaryButtonStyles } from './utils/StylesGenerator';
oke ko udh aku coba pake camelCase nya thankyou ko sarannya

2023-06-28 17:57 UTC, RifianFernando commented on src/components/Button/styles.ts
> +import { generateDefaultPrimarySecondaryButtonStyles } from './utils/StylesGenerator';
kalo nama functionnya gini oke gk ko kira kira namingnya?

2023-06-28 18:45 UTC, RifianFernando commented on src/components/Button/styles.ts
> +        border: 'none !important',
oke ko aman ko udh aku ganti ko

2023-06-29 04:21 UTC, randiadiel approved these changes
Dibenerin ya comment"nya

Besides that lgtm

2023-06-29 04:21 UTC, randiadiel commented on src/components/Button/index.tsx
> +    // const styleProperties = { backgroundColor: btnColor, border: btnColor };
Hmmmmmm

2023-06-29 04:21 UTC, randiadiel commented on src/components/Button/index.tsx
> +                // style={styleProperties}
Hmmmmm

2023-06-29 05:10 UTC, RifianFernando commented on src/components/Button/index.tsx
> +    // const styleProperties = { backgroundColor: btnColor, border: btnColor };
done ko

2023-06-29 05:10 UTC, RifianFernando commented on src/components/Button/index.tsx
> +                // style={styleProperties}
done ko

2023-06-29 05:17 UTC, merged