Tessy/navbar/feature
RnDBNCC/technotic pull request #93
Opened 2023-08-24 01:03 UTC by TessyJr

Developer: Tessy
### Task Summary

Refactored navbar component code structure and stylings

2023-08-28 01:03 UTC, randiadiel requested changes

2023-08-28 01:03 UTC, randiadiel commented on src/components/Navbar/styles.ts
> +    & a.mobileNavLink {
Buat better maintainability, better bikin class buat masing" a dan div ini

Bakal jadi masalah kalo someday org perlu bikin div didalem sana dan tbtb kestyling.. dia harus nyari ini dan ngubah

2023-08-28 01:03 UTC, randiadiel commented on src/components/Navbar/types.ts
> +interface link {
Penamaan type harusnya PascalCase

2023-08-28 04:13 UTC, TessyJr commented on src/components/Navbar/index.tsx
> +            <span></span>
ini menu buttonnya ko, dibikin manual soalnya ada animasi pas di klik

2023-08-28 04:25 UTC, randiadiel commented on src/components/Navbar/index.tsx
> +            <span></span>
Dikasih comment, dijelasin

2023-08-28 08:56 UTC, TessyJr commented on src/components/Navbar/index.tsx
> +        <div className={cx(styles.styNavlinks(fontColor))}>
ini destructure stylesny kyk gmn ya ko mksdny?

2023-08-28 09:14 UTC, TessyJr commented on src/components/Navbar/index.tsx
> +        <div className={cx(styles.styNavlinks(fontColor))}>
`import { styNavbarButton } from './styles';`

Begini kah ko mknsdy?

2023-08-28 09:40 UTC, randiadiel commented on src/components/Navbar/index.tsx
> +        <div className={cx(styles.styNavlinks(fontColor))}>
Iya kayak gitu

Tapi as you do that, lu import semua wapaupun belum tentu semuanya dipake kan(?)

Lu import * berarti otomatis semuanya msk ke styles object lu

Trus lu do repetitive actions banyak banget styles.blabla.. yang harusnya bisa langsung blabla aja

2023-08-28 09:40 UTC, randiadiel commented on src/components/Navbar/index.tsx
> +        <div className={cx(styles.styNavlinks(fontColor))}>
Kedua, kalau lu sampe ngerasa itu kepanjangan, berarti components lu terlalu gede.

2023-08-28 09:42 UTC, randiadiel commented on src/components/Navbar/index.tsx
> +        <div className={cx(styles.styNavlinks(fontColor))}>
Bisa baca ini https://react.dev/learn/thinking-in-react

Kalau lu udh ngikutin cara berfikirnya yang bahkan di state di docs resminya.. 

Seharusnya import lu gabakal panjang

2023-08-28 09:44 UTC, randiadiel commented on src/components/Navbar/index.tsx
> +        <div className={cx(styles.styNavlinks(fontColor))}>
Coba di reconsider apakah seperating by creating functions di file yang sama works atau engga...

2023-08-28 09:54 UTC, TessyJr commented on src/components/Navbar/index.tsx
> +        <div className={cx(styles.styNavlinks(fontColor))}>
> Tapi as you do that, lu import semua wapaupun belum tentu semuanya dipake kan(?)

Oh ini pasti kepake semua ko, soalnya styles.ts yg di import itu khusus buat componentnya.



> Coba di reconsider apakah seperating by creating functions di file yang sama works atau engga...

Oke ko, artinya kl aku import kyk gini ga masalah kan ya ko
```
import {
    styNavbarContainer,
    styNavbar,
    styNavLinks,
    styHamburgerMenuButton,
    styCrossMenuButton,
    styMobileNavLinksOpen,
    styMobileNavLinksClose,
    styNavbarTitle,
    styNavbarButton,
} from './styles';
```

2023-08-28 12:45 UTC, JonathanChr11 approved these changes

2023-09-01 13:17 UTC, randiadiel commented on src/components/Navbar/index.tsx
> +                    <span className="menuIcon"></span>
karena lu kasih className, jadi sebenernya gaperlu comment, tapi okelah

2023-09-01 13:17 UTC, randiadiel commented on src/components/Navbar/types.ts
> +type PositionType = 'static' | 'relative' | 'fixed' | 'absolute' | 'sticky';
```suggestion
export type PositionType = 'static' | 'relative' | 'fixed' | 'absolute' | 'sticky';
```

2023-09-01 13:17 UTC, randiadiel commented on src/components/Navbar/types.ts
> +export { PositionType };
```suggestion
```

2023-09-01 13:18 UTC, randiadiel approved these changes
tolong benerin dulu sebelum merge ya, gua lepas request changesnya supaya kalo udh dibenerin bs langsung merge.

2023-09-04 01:42 UTC, merged